name: Manual Release Upload

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  upload_release:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 查找符合条件的 ZIP 文件
        run: |
          mkdir -p release_files
          find . -type f -name "AnyKernel3_KernelSU_Next_*.zip" | grep -v "喵喵喵" | xargs -I {} cp {} release_files/
          ls -al release_files/

      - name: 创建 Release（如果不存在）
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          release_name: "Latest Kernel Builds"
          draft: false
          prerelease: false

      - name: 上传符合条件的 ZIP 文件
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release_files/
          asset_name: ${{ github.run_id }}.zip
          asset_content_type: application/zip