name: Upload ZIP files to Release

on:
  push:
    branches:
      - main  # 触发分支

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
    # 获取代码仓库内容
    - name: Checkout code
      uses: actions/checkout@v3

    # 设置 GitHub token 以便于操作 release
    - name: Set up GitHub Token
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # 创建 Release
    - name: Create Release
      id: release
      run: |
        RELEASE_TAG="v$(date +'%Y.%m.%d.%H%M')"
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"tag_name": "'"$RELEASE_TAG"'", "name": "'"$RELEASE_TAG"'", "body": "Release description"}' \
          https://api.github.com/repos/${{ github.repository }}/releases

    # 上传 ZIP 文件到 Release
    - name: Upload ZIP files
      run: |
        for file in $(find . -type f -name "*.zip"); do
          echo "Uploading $file"
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/zip" \
            --data-binary @$file \
            "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.release.outputs.id }}/assets?name=$(basename $file)"
        done